/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PackageOptimizer;

import java.util.ArrayList;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

    }
    public static  List<Integer> optap(List<Integer> input){
        ArrayList newlist=new ArrayList<Integer>(input);
        ArrayList<Integer> pacage = new ArrayList<Integer>(input);
        for (int i = 0; i < pacage.size(); i++) {
            System.out.println(i);
            if(pacage.size()>i+1){
                if(pacage.get(i)>pacage.get(i+1))
                {
                    System.out.println(pacage.get(i)+"*****"+i);
                    pacage.set(i, pacage.get(i)+pacage.get(i+1));
                    pacage.remove(i+1);
                    i--;

                }
                else {
                    continue;
                }
            }}
        return pacage;

    }


}
